version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    shm_size: "256MB"
    command: >
      postgres -c 'max_connections=250'
      && postgres -c 'shared_buffers=256MB'
      && postgres -c 'work_mem=128MB'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432
    volumes:
      - ${HOME}/blockscout-data/postgres-data:/var/lib/postgresql/data
